version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3"
        NODE_VERSION: "none"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - flask_app
    ports:
      - "5000:5000" # app port
      - "5001:5001" # app(debug) port
      - "3000:3000" # remote debugger attach port

networks:
  flask_app:
    driver: bridge

volumes:
  postgres:
  pgadmin: